// playground/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import DemoOnce from './components/DemoOnce.vue'
import DemoStream from './components/DemoStream.vue'
import DemoSfc from './components/DemoSfc.vue'
import DemoDocs from './components/DemoDocs.vue'

const tabs = [
  { key: 'once',   label: '一次性渲染' },
  { key: 'stream', label: '流式渲染'   },
  { key: 'chat',   label: '与大模型对话' },
  { key: 'docs',   label: '📖 文档'    },
] as const

type Tab = typeof tabs[number]['key']
const active = ref<Tab>('once')
</script>

<template>
  <nav>
    <button
      v-for="t in tabs"
      :key="t.key"
      :class="{ active: active === t.key }"
      @click="active = t.key"
    >
      {{ t.label }}
    </button>
  </nav>

  <div class="page">
    <DemoOnce   v-if="active === 'once'"   />
    <DemoStream v-if="active === 'stream'" />
    <DemoSfc    v-if="active === 'chat'"   />
    <DemoDocs   v-if="active === 'docs'"   />
  </div>
</template>

// playground-all/src/react/App.tsx
import { useState } from 'react'
import DemoOnce from './components/DemoOnce.js'
import DemoStream from './components/DemoStream.js'
import DemoDocs from './components/DemoDocs.js'

const tabs = [
  { key: 'once',   label: '一次性渲染' },
  { key: 'stream', label: '流式渲染'   },
  { key: 'docs',   label: '📖 文档'    },
] as const

type Tab = typeof tabs[number]['key']

export default function App() {
  const [active, setActive] = useState<Tab>('once')

  return (
    <>
      <nav>
        {tabs.map((t) => (
          <button
            key={t.key}
            className={active === t.key ? 'active' : ''}
            onClick={() => setActive(t.key)}
          >
            {t.label}
          </button>
        ))}
      </nav>

      <div className="page">
        {active === 'once'   && <DemoOnce />}
        {active === 'stream' && <DemoStream />}
        {active === 'docs'   && <DemoDocs />}
      </div>
    </>
  )
}
