// playground/src/vue2/App.vue
<script lang="ts">
import { defineComponent, ref } from 'vue'
import DemoOnce from './components/DemoOnce.vue'
import DemoStream from './components/DemoStream.vue'

const tabs = [
  { key: 'once',   label: '一次性渲染' },
  { key: 'stream', label: '流式渲染'   },
] as const

type Tab = typeof tabs[number]['key']

export default defineComponent({
  name: 'App',
  components: { DemoOnce, DemoStream },
  setup() {
    const active = ref<Tab>('once')
    return { tabs, active }
  },
})
</script>

<template>
  <!-- Vue 2 requires a single root element -->
  <div>
    <nav>
      <button
        v-for="t in tabs"
        :key="t.key"
        :class="{ active: active === t.key }"
        @click="active = t.key"
      >
        {{ t.label }}
      </button>
    </nav>

    <div class="page">
      <DemoOnce   v-if="active === 'once'"   />
      <DemoStream v-if="active === 'stream'" />
    </div>
  </div>
</template>

// playground-all/src/react/App.tsx
import { useState } from 'react'
import DemoOnce from './components/DemoOnce.js'
import DemoStream from './components/DemoStream.js'
import DemoDocs from './components/DemoDocs.js'

const tabs = [
  { key: 'once',   label: '一次性渲染' },
  { key: 'stream', label: '流式渲染'   },
  { key: 'docs',   label: '📖 文档'    },
] as const

type Tab = typeof tabs[number]['key']

export default function App() {
  const [active, setActive] = useState<Tab>('once')

  return (
    <>
      <nav>
        {tabs.map((t) => (
          <button
            key={t.key}
            className={active === t.key ? 'active' : ''}
            onClick={() => setActive(t.key)}
          >
            {t.label}
          </button>
        ))}
      </nav>

      <div className="page">
        {active === 'once'   && <DemoOnce />}
        {active === 'stream' && <DemoStream />}
        {active === 'docs'   && <DemoDocs />}
      </div>
    </>
  )
}
