// playground/src/react/components/DemoOnce.tsx
import { useState } from 'react'
import { MarkdownWithTokens } from '../tokens.js'
import TEMPLATE from '../../shared/tokens.md?raw'

export default function DemoOnce() {
  const [source, setSource] = useState(TEMPLATE)
  const [rendered, setRendered] = useState(TEMPLATE)

  return (
    <div>
      <div className="controls">
        <button className="run" onClick={() => setRendered(source)}>
          渲染
        </button>
      </div>
      <div className="panel">
        <div className="box">
          <h3>Markdown 输入</h3>
          <textarea
            value={source}
            rows={30}
            onChange={(e) => setSource(e.target.value)}
          />
        </div>
        <div className="box">
          <h3>渲染结果</h3>
          <MarkdownWithTokens content={rendered} debug />
        </div>
      </div>
    </div>
  )
}

// playground/src/vue2/components/DemoOnce.vue
<script lang="ts">
import { defineComponent, ref } from 'vue'
import { MarkdownWithTokens } from '../tokens'
import TEMPLATE from '../../shared/tokens.md?raw'

export default defineComponent({
  name: 'DemoOnce',
  components: { MarkdownWithTokens },
  setup() {
    const source = ref(TEMPLATE)
    const rendered = ref(TEMPLATE)

    function render() {
      rendered.value = source.value
    }

    return { source, rendered, render }
  },
})
</script>

<template>
  <div>
    <div class="controls">
      <button class="run" @click="render">渲染</button>
    </div>
    <div class="panel">
      <div class="box">
        <h3>Markdown 输入</h3>
        <textarea v-model="source" :rows="30" />
      </div>
      <div class="box">
        <h3>渲染结果</h3>
        <MarkdownWithTokens :content="rendered" :debug="false" />
      </div>
    </div>
  </div>
</template>
