// playground-all/src/react/components/DemoStream.tsx
import { useState, useRef } from 'react'
import { MarkdownWithTokens } from '../tokens.js'
import TEMPLATE from '../tokens.md?raw'

const CHUNKS = TEMPLATE.split('\n')

async function* makeStream(ms: number): AsyncIterable<string> {
  for (const chunk of CHUNKS) {
    await new Promise((r) => setTimeout(r, ms))
    yield chunk + '\n'
  }
}

export default function DemoStream() {
  const [delay, setDelay] = useState(200)
  const [stream, setStream] = useState<AsyncIterable<string> | undefined>()
  const [isRunning, setIsRunning] = useState(false)
  // key 用于强制重建 MarkdownStream（切换新流时重置组件内部状态）
  const keyRef = useRef(0)
  const [key, setKey] = useState(0)

  function start() {
    setIsRunning(true)
    setStream(undefined)
    setTimeout(() => {
      keyRef.current += 1
      setKey(keyRef.current)
      setStream(makeStream(delay))
      setIsRunning(false)
    }, 50)
  }

  return (
    <div>
      <div className="controls">
        <button className="run" disabled={isRunning} onClick={start}>
          ▶ 开始流式输出
        </button>
        <label>
          延迟
          <input
            type="range"
            value={delay}
            min={80}
            max={500}
            onChange={(e) => setDelay(Number(e.target.value))}
          />
          {delay}ms
        </label>
      </div>
      <div className="box">
        <h3>渲染结果（含所有自定义 Token）</h3>
        {stream ? (
          <MarkdownWithTokens key={key} content={stream} cursor />
        ) : (
          <p style={{ color: '#9ca3af', fontSize: 13 }}>点击按钮开始流式渲染</p>
        )}
      </div>
    </div>
  )
}

// playground/src/components/DemoStream.vue
<script setup lang="ts">
import { ref } from 'vue'
import { MarkdownWithTokens } from '../tokens'
import TEMPLATE from '../tokens.md?raw'

const CHUNKS = TEMPLATE.split('\n')

const delay = ref(200)
const stream = ref<AsyncIterable<string> | undefined>()
const isRunning = ref(false)

async function* makeStream(ms: number): AsyncIterable<string> {
  for (const chunk of CHUNKS) {
    await new Promise(r => setTimeout(r, ms))
    yield chunk + '\n'
  }
}

function start() {
  isRunning.value = true
  stream.value = undefined
  setTimeout(() => {
    stream.value = makeStream(delay.value)
    isRunning.value = false
  }, 50)
}
</script>

<template>
  <div>
    <div class="controls">
      <button class="run" :disabled="isRunning" @click="start">▶ 开始流式输出</button>
      <label>延迟 <input type="range" v-model.number="delay" min="80" max="500" /> {{ delay }}ms</label>
    </div>
    <div class="box">
      <h3>渲染结果（含所有自定义 Token）</h3>
      <MarkdownWithTokens v-if="stream" :content="stream" />
      <p v-else style="color:#9ca3af;font-size:13px">点击按钮开始流式渲染</p>
    </div>
  </div>
</template>
