// vue3/src/components/MarkdownStream.vue
<script lang="ts">
import { defineComponent, h, provide, watch, markRaw, toRaw, computed } from 'vue'
import type { PropType } from 'vue'
import type { TokenTypeDefinition } from '@markdown-stream/core'
import { useMarkdownStream } from '../composables/use-markdown-stream.js'
import MarkdownTokenNode, { COMPONENTS_INJECT_KEY } from './MarkdownTokenNode.vue'
import type { CustomTokenDefinition, MarkdownTokenComponentMap } from '../types/renderer.js'
import { extractTokenTypes, extractComponentMap } from '../renderers/build-token-type.js'

export default defineComponent({
  name: 'MarkdownStream',
  props: {
    content: {
      type: [Object, String] as PropType<string | AsyncIterable<string>>,
      default: undefined,
    },
    source: {
      type: String as PropType<string>,
      default: undefined,
    },
    stream: {
      type: [Object, String] as PropType<AsyncIterable<string> | string>,
      default: undefined,
    },
    tokenTypes: {
      type: Array as PropType<TokenTypeDefinition[]>,
      default: undefined,
    },
    components: {
      type: [Array, Object] as PropType<
        CustomTokenDefinition[] | Partial<MarkdownTokenComponentMap>
      >,
      default: undefined,
    },
    debug: {
      type: Boolean,
      default: false,
    },
    cursor: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    // 从 components 中提取自动生成的 tokenTypes（首次读取，不追踪后续变化）
    const autoTokenTypes = Array.isArray(props.components)
      ? extractTokenTypes(props.components)
      : []

    const { tokens, isStreaming, consume, parse, reset, cancel } = useMarkdownStream({
      tokenTypes: [...(props.tokenTypes ?? []), ...autoTokenTypes],
      debug: props.debug,
    })

    // 构建 name → Component 映射
    // 数组格式：makeStateRouter 内部已经处理了 toRaw + markRaw，直接使用
    // 旧对象格式：手动 markRaw 每个 Component
    function buildComponentMap(): Record<string, unknown> {
      if (!props.components) return {}
      if (Array.isArray(props.components)) {
        // extractComponentMap 内部调用 makeStateRouter，已处理响应式
        return extractComponentMap(props.components as CustomTokenDefinition[])
      }
      // 旧格式 Record<string, Component>：toRaw 拿到原始对象后 markRaw
      const safe: Record<string, unknown> = {}
      for (const [k, v] of Object.entries(toRaw(props.components))) {
        if (v) safe[k] = markRaw(toRaw(v as object))
      }
      return safe
    }

    provide(COMPONENTS_INJECT_KEY, computed(() => buildComponentMap()))

    // Priority: content > source > stream
    // Note: Vue automatically stops this watcher on unmount.
    // The async consume loop is cancelled via useMarkdownStream's onUnmounted hook.
    watch(
      [() => props.content, () => props.source, () => props.stream],
      ([content, source, stream], prevVals) => {
        const value = content ?? source ?? stream
        if (value === undefined) return

        // Streaming → Static transition: cancel async loop, then parse final text.
        const prevValue = prevVals ? (prevVals[0] ?? prevVals[1] ?? prevVals[2]) : undefined
        const wasStreaming = prevValue != null && typeof prevValue !== 'string'
        if (wasStreaming && typeof value === 'string') {
          cancel()
          isStreaming.value = false
          parse(value)
          return
        }

        reset()
        if (typeof value === 'string') {
          parse(value)
        } else {
          consume(value)
        }
      },
      { immediate: true }
    )

    return () => {
      const children = tokens.value.map((token) =>
        h(MarkdownTokenNode, { key: token.id, token })
      )
      return h(
        'div',
        {
          class: 'ms-root',
          'data-streaming': isStreaming.value ? '' : undefined,
          'data-no-cursor': !props.cursor ? '' : undefined,
        },
        children
      )
    }
  },
})
</script>

// react/src/components/MarkdownStream.tsx
import React, { useEffect, useRef, useMemo } from 'react'
import { useMarkdownStream } from '../hooks/use-markdown-stream.js'
import { MarkdownTokenNode, ComponentsContext, StreamingContext } from './MarkdownTokenNode.js'
import type { MarkdownStreamProps } from '../types/props.js'
import type { CustomTokenDefinition } from '../types/renderer.js'
import { extractTokenTypes, extractComponentMap } from '../renderers/build-token-type.js'

export function MarkdownStream({
  content,
  source,
  stream,
  tokenTypes,
  components,
  debug,
  cursor = false,
  className,
}: MarkdownStreamProps) {
  // Extract token types from custom components array — only on mount, not reactive
  const autoTokenTypesRef = useRef(
    Array.isArray(components) ? extractTokenTypes(components as CustomTokenDefinition[]) : []
  )

  const { tokens, isStreaming, error, consume, parse, reset, cancel } = useMarkdownStream({
    tokenTypes: [...(tokenTypes ?? []), ...autoTokenTypesRef.current],
    debug,
  })

  // Build component map — same as Vue: evaluated once, not reactive
  const componentMap = useMemo(() => {
    if (!components) return {}
    if (Array.isArray(components)) {
      return extractComponentMap(components as CustomTokenDefinition[])
    }
    return components
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const prevValueRef = useRef<string | AsyncIterable<string> | undefined>(undefined)

  useEffect(() => {
    const value = content ?? source ?? stream
    if (value === undefined) return
    let cancelled = false

    const prevValue = prevValueRef.current
    prevValueRef.current = value

    // Streaming → Static transition: cancel async loop, then parse final text.
    const wasStreaming = prevValue != null && typeof prevValue !== 'string'
    if (wasStreaming && typeof value === 'string') {
      cancel()
      parse(value)
      return
    }

    reset()
    if (typeof value === 'string') {
      parse(value)
    } else {
      // Delay async consumption by one microtask so React StrictMode's
      // mount/unmount rehearsal does not consume single-use streams.
      queueMicrotask(() => {
        if (cancelled) return
        void consume(value)
      })
      return () => {
        cancelled = true
      }
    }
  }, [content, source, stream]) // eslint-disable-line react-hooks/exhaustive-deps

  const rootClass = ['ms-root', className].filter(Boolean).join(' ')

  return (
    <ComponentsContext.Provider value={componentMap}>
      <StreamingContext.Provider value={isStreaming}>
        <div
          className={rootClass}
          data-streaming={isStreaming ? '' : undefined}
          data-no-cursor={!cursor ? '' : undefined}
        >
          {tokens.map((token) => (
            <MarkdownTokenNode key={token.id} token={token} />
          ))}
          {error != null && (
            <div className="ms-stream-error" role="alert">
              {error instanceof Error ? error.message : String(error)}
            </div>
          )}
        </div>
      </StreamingContext.Provider>
    </ComponentsContext.Provider>
  )
}
